/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BackgroundStyle = { 'starfield' : null } |
  { 'spaceNebula' : null } |
  { 'darkOcean' : null } |
  { 'matrixCode' : null } |
  { 'cyberForest' : null } |
  { 'abstractGlitch' : null } |
  { 'solidDark' : null } |
  { 'particleGrid' : null } |
  { 'neonCity' : null } |
  { 'neonRain' : null } |
  { 'cyberHexGrid' : null };
export type CursorStyle = { 'arrowGlow' : null } |
  { 'starBurst' : null } |
  { 'neonDot' : null } |
  { 'crosshair' : null } |
  { 'ringPulse' : null };
export type FontStyle = { 'orbitron' : null } |
  { 'sansSerif' : null } |
  { 'monospace' : null } |
  { 'rajdhani' : null } |
  { 'pressStart2P' : null };
export interface Preferences {
  'cursorStyle' : CursorStyle,
  'lastActiveTab' : string,
  'fontStyle' : FontStyle,
  'backgroundStyle' : BackgroundStyle,
  'notepad' : string,
  'cloakPreset' : TabCloakPreset,
  'accentColor' : string,
}
export type TabCloakPreset = { 'clever' : null } |
  { 'google' : null } |
  { 'default' : null } |
  { 'youtube' : null } |
  { 'googleClassroom' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCCoins' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCCoins' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPreferences' : ActorMethod<[], Preferences>,
  'getPurchasedEffects' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveNotepad' : ActorMethod<[string], undefined>,
  'savePreferences' : ActorMethod<
    [string, string, CursorStyle, BackgroundStyle, FontStyle, TabCloakPreset],
    undefined
  >,
  'setPurchasedEffects' : ActorMethod<[Array<string>], undefined>,
  'spendCCoins' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];